"""
Application Constants and Design Tokens
"""

# User Roles
ROLE_ADMIN = "admin"
ROLE_OPERATOR = "operator"
ROLE_VIEWER = "viewer"

ROLES = [ROLE_ADMIN, ROLE_OPERATOR, ROLE_VIEWER]

# Gate States
GATE_STATE_OPEN = "OPEN"
GATE_STATE_CLOSED = "CLOSED"
GATE_STATE_OPENING = "OPENING"
GATE_STATE_CLOSING = "CLOSING"
GATE_STATE_ERROR = "ERROR"

GATE_STATES = [
    GATE_STATE_OPEN,
    GATE_STATE_CLOSED,
    GATE_STATE_OPENING,
    GATE_STATE_CLOSING,
    GATE_STATE_ERROR,
]

# Gate Modes
GATE_MODE_AUTO = "AUTO"
GATE_MODE_MANUAL = "MANUAL"
GATE_MODES = [GATE_MODE_AUTO, GATE_MODE_MANUAL]

# Sensor Types
SENSOR_TYPE_LEVEL = "level"
SENSOR_TYPE_FLOW = "flow"
SENSOR_TYPE_PRESSURE = "pressure"
SENSOR_TYPE_PH = "ph"
SENSOR_TYPE_TURBIDITY = "turbidity"
SENSOR_TYPE_QUALITY = "quality"

SENSOR_TYPES = [
    SENSOR_TYPE_LEVEL,
    SENSOR_TYPE_FLOW,
    SENSOR_TYPE_PRESSURE,
    SENSOR_TYPE_PH,
    SENSOR_TYPE_TURBIDITY,
    SENSOR_TYPE_QUALITY,
]

# Alert Severities
ALERT_SEVERITY_CRITICAL = "critical"
ALERT_SEVERITY_WARNING = "warning"
ALERT_SEVERITY_INFO = "info"

ALERT_SEVERITIES = [
    ALERT_SEVERITY_CRITICAL,
    ALERT_SEVERITY_WARNING,
    ALERT_SEVERITY_INFO,
]

# Distribution Step & Sequence Statuses
STATUS_COMPLETED = "COMPLETED"
STATUS_ACTIVE = "ACTIVE"
STATUS_WAITING = "WAITING"
STATUS_FAILED = "FAILED"

DISTRIBUTION_STATUSES = [
    STATUS_COMPLETED,
    STATUS_ACTIVE,
    STATUS_WAITING,
    STATUS_FAILED,
]

# UI Design System Color Palette (PRD Specs)
COLOR_BACKGROUND = "#F7F8FA"
COLOR_SURFACE = "#FFFFFF"
COLOR_TEXT_PRIMARY = "#111827"
COLOR_TEXT_SECONDARY = "#6B7280"
COLOR_BORDER = "#E5E7EB"

COLOR_PRIMARY = "#2563EB"       # Blue
COLOR_ACCENT = "#06B6D4"        # Teal / Water

COLOR_SUCCESS = "#10B981"       # Green
COLOR_WARNING = "#F59E0B"       # Amber
COLOR_CRITICAL = "#DC2626"      # Red
COLOR_INFO = "#3B82F6"          # Light Blue
COLOR_MUTED = "#9CA3AF"         # Gray
